language: node_js
node_js:
  - '5'
before_deploy: "sh deploy-travis.sh"
deploy:
  provider: releases
  api_key:
    secure: kXPvD4CKe7O6lUbqAS8/HmPehwmUxxIXYxiaqzzxBF0HUzdS+LCtZLTksiSxFCOnThvooskOjLzE52V2141kBUjqlKmn/T+HycD/b2mbQdr3UbZl1Ghplu3t3eQ521y7pX1kNl3qFPy7MhZKNgAtMmL6zL47AzOm+VSVKW2JPSqBq1kLZCm4SmutnKWMuX9eUdvNMazse3fBdGbYzm7GNzYse65Hg61PJQsJRXPjQGvovmipmkY1OHEH6IbndxYaNwZ5fOazLyOOrtL0RtnjbNxMIHuK5l87Lz1E9GpgJjbuUhoS7gGc65AScBn34/tN1U57hDTcNFDTaKpEqYSURJ9PDO9lPNO4+b1ny9JcXU/O9eyVQxXAfUnMoax7szwYJUgCEp0tmGgxW+aCknC2U+UboGy0hoWjqTv4/XMA4zDAQuLeXAOweM+ap5d0kWtRSnwgan7EHhGIMLIUpbwPYf6vFGk4mjbiqC42C3LzP0er5HodMEynLGXneFR6aEwXHPnSF7UAAaPfRRmBKaN0XJH8Ey3lu1X/yzVbwd8GHS3jDPBIvQaRrl+w3hVs3o+0b/SI4ikJqH5HavZI8Uik1hhD89puLiIuewljMHc/vvB7GXdmYLvbjKtFfhIb9mMi8+0c0IQU2nJQhfmtjstwWBZ8AM/NyGP+eXlRLps1aVg=
  file: "dist-pkg/installers/record-desktop_${TRAVIS_TAG}_amd64.deb"
  skip_cleanup: true
  on:
    tags: true
